/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IaVisaoRouteImport } from './routes/ia-visao'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated/conferencia'
import { Route as AuthenticatedConferenciasRouteImport } from './routes/_authenticated/conferencias'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedEntradaDocumentoRouteImport } from './routes/_authenticated/entrada-documento'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedMediasRouteImport } from './routes/_authenticated/medias'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRecebimentoRouteImport } from './routes/_authenticated/recebimento'
import { Route as AuthenticatedRecibosRouteImport } from './routes/_authenticated/recibos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSaidaRouteImport } from './routes/_authenticated/saida'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IaVisaoRoute = IaVisaoRouteImport.update({
  id: '/ia-visao',
  path: '/ia-visao',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenciasRoute =
  AuthenticatedConferenciasRouteImport.update({
    id: '/conferencias',
    path: '/conferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaDocumentoRoute =
  AuthenticatedEntradaDocumentoRouteImport.update({
    id: '/entrada-documento',
    path: '/entrada-documento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediasRoute = AuthenticatedMediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecibosRoute = AuthenticatedRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecebimentoRoute =
  AuthenticatedRecebimentoRouteImport.update({
    id: '/recebimento',
    path: '/recebimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaidaRoute = AuthenticatedSaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/ia-visao': typeof IaVisaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/setup': typeof SetupRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/conferencias': typeof AuthenticatedConferenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/entrada-documento': typeof AuthenticatedEntradaDocumentoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/medias': typeof AuthenticatedMediasRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/saida': typeof AuthenticatedSaidaRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/ia-visao': typeof IaVisaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/setup': typeof SetupRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/conferencias': typeof AuthenticatedConferenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/entrada-documento': typeof AuthenticatedEntradaDocumentoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/medias': typeof AuthenticatedMediasRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recebimento': typeof AuthenticatedRecebimentoRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/saida': typeof AuthenticatedSaidaRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/ia-visao': typeof IaVisaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/setup': typeof SetupRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/conferencias': typeof AuthenticatedConferenciasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/entrada-documento': typeof AuthenticatedEntradaDocumentoRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/medias': typeof AuthenticatedMediasRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/recebimento': typeof AuthenticatedRecebimentoRoute
  '/_authenticated/recibos': typeof AuthenticatedRecibosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/saida': typeof AuthenticatedSaidaRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/ia-visao'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/setup'
    | '/conferencia'
    | '/conferencias'
    | '/configuracoes'
    | '/dashboard'
    | '/entrada'
    | '/entrada-documento'
    | '/estoque'
    | '/historico'
    | '/medias'
    | '/produtos'
    | '/recebimento'
    | '/relatorios'
    | '/saida'
    | '/unidades'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/ia-visao'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/setup'
    | '/conferencia'
    | '/conferencias'
    | '/configuracoes'
    | '/dashboard'
    | '/entrada'
    | '/entrada-documento'
    | '/estoque'
    | '/historico'
    | '/medias'
    | '/produtos'
    | '/recebimento'
    | '/relatorios'
    | '/saida'
    | '/unidades'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/ia-visao'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/setup'
    | '/_authenticated/conferencia'
    | '/_authenticated/conferencias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrada'
    | '/_authenticated/entrada-documento'
    | '/_authenticated/estoque'
    | '/_authenticated/historico'
    | '/_authenticated/medias'
    | '/_authenticated/produtos'
    | '/_authenticated/recebimento'
    | '/_authenticated/relatorios'
    | '/_authenticated/saida'
    | '/_authenticated/unidades'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  IaVisaoRoute: typeof IaVisaoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-visao': {
      id: '/ia-visao'
      path: '/ia-visao'
      fullPath: '/ia-visao'
      preLoaderRoute: typeof IaVisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conferencias': {
      id: '/_authenticated/conferencias'
      path: '/conferencias'
      fullPath: '/conferencias'
      preLoaderRoute: typeof AuthenticatedConferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada-documento': {
      id: '/_authenticated/entrada-documento'
      path: '/entrada-documento'
      fullPath: '/entrada-documento'
      preLoaderRoute: typeof AuthenticatedEntradaDocumentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medias': {
      id: '/_authenticated/medias'
      path: '/medias'
      fullPath: '/medias'
      preLoaderRoute: typeof AuthenticatedMediasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recebimento': {
      id: '/_authenticated/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof AuthenticatedRecebimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saida': {
      id: '/_authenticated/saida'
      path: '/saida'
      fullPath: '/saida'
      preLoaderRoute: typeof AuthenticatedSaidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedConferenciasRoute: typeof AuthenticatedConferenciasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
  AuthenticatedEntradaDocumentoRoute: typeof AuthenticatedEntradaDocumentoRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMediasRoute: typeof AuthenticatedMediasRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRecebimentoRoute: typeof AuthenticatedRecebimentoRoute
  AuthenticatedRecibosRoute: typeof AuthenticatedRecibosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSaidaRoute: typeof AuthenticatedSaidaRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedConferenciasRoute: AuthenticatedConferenciasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
  AuthenticatedEntradaDocumentoRoute: AuthenticatedEntradaDocumentoRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMediasRoute: AuthenticatedMediasRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRecebimentoRoute: AuthenticatedRecebimentoRoute,
  AuthenticatedRecibosRoute: AuthenticatedRecibosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSaidaRoute: AuthenticatedSaidaRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  IaVisaoRoute: IaVisaoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
